services:
  app:
    image: ghcr.io/remla23-team17/app:latest
    ports:
      - "8081:8081"
    networks:
      network:
        ipv4_address: 172.20.0.3
    depends_on:
      - model-service
    environment:
      MODEL_SERVICE_HOST: "http://model-service:8080/predict"

  model-service:
    image: ghcr.io/remla23-team17/model-service:latest
    ports:
      - "8080:8080"
    networks:
      network:
        ipv4_address: 172.20.0.2
      

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
