services:
  app:
    image: ghcr.io/remla23-team17/app:0.0.4
    ports:
      - "80:80"
    networks:
      network:
        ipv4_address: 172.20.0.3
    depends_on:
      - model-service
    environment:
      MODEL_SERVICE_HOST: "http://model-service/predict"
      EXPOSE_PORT: 80

  model-service:
    image: ghcr.io/remla23-team17/model-service:0.0.4
#    ports: # No need to open model-service to the host, only open for debugging purposes.
#      - "81:80"
    networks:
      network:
        ipv4_address: 172.20.0.2
      

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
