apiVersion: v1
kind: Service
metadata:
  name: model-service
spec:
  type: ClusterIP
  selector:
    component: model-service
  ports:
    - port: 80
      name: http
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: model-service
  template:
    metadata:
      labels:
        component: model-service
    spec:
      containers:
        - name: model-service
          image: ghcr.io/remla23-team17/model-service:1.0.0
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          ports:
            - containerPort: 80
          env:
            - name: MODEL_URL
              value: "https://github.com/remla23-team17/model-training/releases/latest/download/model"
            - name: BOW_URL
              value: "https://github.com/remla23-team17/model-training/releases/latest/download/bow.pkl"